# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
  configs:
    my_config_1:
      toolbar: "my_toolbar_1"
  toolbars:
    configs:
      my_toolbar_1: [ [ "Bold", "-", "Italic", "-", "Underline", "-", "TextColor", "-", "FontSize", "-", "AlignCenter" ] ]

#twig:
#    form_themes:
#        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
